language: java
jdk:
    - openjdk8
node_js: "10"

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm

script:
  - ./build.sh

before_deploy:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
