language: java
jdk:
    - openjdk8
node_js: "10"

cache:
  directories:
  - $HOME/.m2
  - w/node_modules

before_script:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
script:
  - ./build_b.sh
deploy:
  provider: script
  script: bash deploy_b.sh
  on:
    branch: deploy
