language: java
jdk:
    - openjdk8
node_js: "10"

cache:
  directories:
  - $HOME/.m2
  - $HOME/.npm

 script:
  - ./build_b.sh
  - ./build_w.sh

before_deploy:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy_b.sh
  on:
    branch: deploy
