image: maven:3-jdk-8

stages:
- verify
- deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
  - .m2/repository
  - godzula/target

verify:
  stage: verify
  script:
  - mvn -pl godzula -Pprod clean verify
  except:
  - deploy

verify_prod:
  stage: verify
  services:
    - mongo:latest
  script:
  - mvn -pl godzula -P prod,integrationTests clean verify
  only:
  - deploy

deploy:
  stage: deploy
  script:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - cd godzula
  - heroku plugins:install java
  - heroku deploy:jar target/*.war --app godzula
  only:
  - deploy
